name: ai_chatbot
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.14.0
  dash_chat_2: 0.0.19
  dotenv: ^4.2.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  google_sign_in: 6.1.6
  http: 1.1.0
  image_picker: ^1.0.7
  package_info_plus: 4.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

fonts:
  - family: MontSerrat
    fonts:
      - asset: assets/fonts/Montserrat-Italic.ttf
        style: italic
      - asset: assets/fonts/fonts/Montserrat-ExtraBold.ttf
        style: 800
